apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-services
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-services
  template:
    metadata:
      name: order-services
      labels:
        app: order-services
    spec:
      containers:
        - name: order-services
          image: nvlannasik/order-services-nodejs:release-1.0.3
          ports:
            - name: order-svc
              containerPort: 3000
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: order-configmap
            - secretRef:
                name: order-services-secret
