apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  name: configmap-generator-prod-fe
  labels:
    app: configmap-generator-prod-fe
configMapGenerator:
  - name: configmap-fe
    env: config.properties
    options:
      disableNameSuffixHash: true
