apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-services
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-services
  template:
    metadata:
      name: product-services
      labels:
        app: product-services
    spec:
      containers:
        - name: product-services
          image: nvlannasik/product-services-nodejs:release-1.0.3
          ports:
            - name: product-svc
              containerPort: 3000
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: product-configmap
            - secretRef:
                name: product-services-secret
