apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  name: configmap-generator-prod-be
  labels:
    app: configmap-generator-prod-be
configMapGenerator:
  - name: configmap-be
    env: config.properties
    options:
      disableNameSuffixHash: true
