apiVersion: v1
kind: Service
metadata:
  name: product-services-svc
  namespace: default
spec:
  selector:
    app: product-services
  ports:
    - port: 3000
      targetPort: 3000
  clusterIP: None
